language: node_js
sudo: false
dist: trusty
node_js:
    - "8"

addons:
    - filefox : latext

before_install:
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

